[versions]
serialization = "1.4.1"
uuidVersion = "0.3.1"
coroutines = "1.6.4"
activityVersion = "1.6.1"
appCompatVersion = "1.6.1"
composeVersion = "1.3.3"

minSdk = "24"
compileSdk = "33"
targetSdk = "33"

packageName = "io.github.alexgladkov"
packageVersion = "1.4.0"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines"}
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines"}
coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines"}

test-compose-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeVersion"}
test-compose-manifest = { module = "androidx.compose.ui:ui-test-manifest" , version.ref = "composeVersion"}

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityVersion" }
activity-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompatVersion" }

uuid = { module = "com.benasher44:uuid", version.ref = "uuidVersion"}

kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }