name: ComposeOdysseyDemo
options:
  bundleIdPrefix: ru.alexgladkov
settings:
  DEVELOPMENT_TEAM: 8KLS9QG6WN
  CODE_SIGN_IDENTITY: "iPhone Developer"
  CODE_SIGN_STYLE: Automatic
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "4"
  SDKROOT: iphoneos
targets:
  ComposeOdysseyDemo:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    prebuildScripts:
      - script: cd "$SRCROOT" && cd .. && ./gradlew -i -p . packForXCode
        name: GradleCompile
    info:
      path: plists/Ios/Info.plist
      properties:
        UILaunchStoryboardName: ""
    sources:
      - "../common/common-root/src/"
    settings:
      LIBRARY_SEARCH_PATHS: "$(inherited)"
      ENABLE_BITCODE: "YES"
      ONLY_ACTIVE_ARCH: "NO"
      VALID_ARCHS: "arm64"