name: Test

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-macos-latest:
    name: Run build on PR to main
    runs-on: macos-latest,

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: { java-version: 15 }
      - name: Build targets
        run: ./gradlew build